# Virtual☆Paradise hyprlock configuration

$color = rgba(7, 8, 13, 1)
$inner_color = rgba(7, 8, 13, 0.75)
$outer_color = rgba(0, 245, 212, 1)
$font_color = rgba(234, 251, 250, 1)
$placeholder_color = rgba(82, 110, 127, 0.8)
$check_color = rgba(0, 255, 136, 1)