# Virtual☆Paradise ghostty configuration

background = #07080d
foreground = #eafbfa
background-opacity = 0.85
cursor-color = #00f5d4
selection-background = #00f5d4
selection-foreground = #07080d

# Standard colors
palette = 0=#07080d
palette = 1=#ff5287
palette = 2=#00ff88
palette = 3=#ffe066
palette = 4=#00f5d4
palette = 5=#ffb7d5
palette = 6=#39c5bb
palette = 7=#eafbfa

# Bright colors
palette = 8=#526e7f
palette = 9=#ff79a8
palette = 10=#39ff14
palette = 11=#fff099
palette = 12=#5effeb
palette = 13=#ffd6e7
palette = 14=#70f3ff
palette = 15=#ffffff