# Virtual☆Paradise kitty configuration

background #07080d
foreground #eafbfa
background_opacity 0.85
cursor #00f5d4
cursor_text_color #07080d
selection_background #00f5d4
selection_foreground #07080d

# Black
color0 #07080d
color8 #526e7f

# Red
color1 #ff5287
color9 #ff79a8

# Green
color2 #00ff88
color10 #39ff14

# Yellow
color3 #ffe066
color11 #fff099

# Blue
color4 #00f5d4
color12 #5effeb

# Magenta
color5 #ffb7d5
color13 #ffd6e7

# Cyan
color6 #39c5bb
color14 #70f3ff

# White
color7 #eafbfa
color15 #ffffff